//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba_jaramillo_villegas.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BasculaEntities : DbContext
    {
        public BasculaEntities()
            : base("name=BasculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Duplicado> Duplicados { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
    
        public virtual int InserDataProcedure(string variableSent, Nullable<System.DateTime> dateSent)
        {
            var variableSentParameter = variableSent != null ?
                new ObjectParameter("variableSent", variableSent) :
                new ObjectParameter("variableSent", typeof(string));
    
            var dateSentParameter = dateSent.HasValue ?
                new ObjectParameter("dateSent", dateSent) :
                new ObjectParameter("dateSent", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InserDataProcedure", variableSentParameter, dateSentParameter);
        }
    }
}
